### ISSUE TITLE
Plugins/PRISM can't use

### ISSUE THREAD

**Issue by Blazer7** [IbisNeuronav/Ibis#354]
When I add the​ ​ Ray​ ​ Init​ ​ shader,  once I hit OK, the software will crash. 

![2020-09-11 19-41-42屏幕截图](https://user-images.githubusercontent.com/43225930/92923175-96627600-f469-11ea-919e-a353f5c515ea.png)

The code  as follows.
ASSERT: "index < GetNumberOfRayInitShaderTypes() && index >= 0" in file /home/blaze/basedir/src/IbisPlugins/PRISMVolumeRender/volumerenderingobject.cpp, line 733

**Comment by Blazer7** [comment]
My system is ubuntu1804

**Comment by hgueziri** [comment]
This should fix the issue (#355).

**Comment by Blazer7** [comment]
> This should fix the issue (#355).
Thank you, but the issue is still here.
The code is still the same as above.
After I update the code,  can I just run the software directly?  Do I need to ‘make’ it again?

**Comment by Blazer7** [comment]
> 这应该可以解决该问题（[＃355](https://github.com/IbisNeuronav/Ibis/pull/355)）。

Thank you, but the issue is still here.
The code is still the same as above.
After I update the code, can I just run the software directly? Do I need to ‘make’ it again?

**Comment by Blazer7** [comment]
> This should fix the issue (#355).
Thank you, but the issue is still here.
The code is still the same as above.
After I update the code, can I just run the software directly? Do I need to ‘make’ it again?

**Comment by Blazer7** [comment]
Thank you, the issue has fixed.
But there is another issue. When I add the​ ​ Stop Condition ​ shader, the software will crash again.
![2020-09-12 14-49-24屏幕截图](https://user-images.githubusercontent.com/43225930/92990231-4d63fd80-f50d-11ea-9d8c-c449f903e175.png)
The code as follows:
ASSERT: "index < GetNumberOfStopConditionShaderTypes() && index >= 0" in file /home/blaze/basedir/src/IbisPlugins/PRISMVolumeRender/volumerenderingobject.cpp, line 866

**Comment by hgueziri** [comment]
Thanks for highlighting this issue. It was caused by typos in variable/function names. I made the changes in #356 
Let me know if this fix the problem.

You need to make a `git pull` then run `make` to take the changes into account

**Comment by Blazer7** [comment]
The issue has been solved. thank you.
I want to know where to find the variable names that need to be passed when building a new code in the Ray Init module?
I want to implement Algorithm 2 in the following article. [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5849289/](url)
Algorithm 2 in the article is as follows:
`// Determine if ray is intersecting the sphere`
`vec3 centerDir = interactionPoint1−rayStart;`
`float centerProjDist = dot (centerDir, rayDir);`
`vec3 centerProj = rayStart + rayDir *centerProjDist;`
`float distCenterProjCenter = length(centerProj−interactionPoint1);`
`// if we have an intersection,adjust ray integration start`
`float sphereRadius = 0.5;`
`if(distCenterProjCenter <sphereRadius)`
`{`
`  float dcpc2 = distCenterProjCenter *distCenterProjCenter;`
`  float sr2 = sphereRadius *sphereRadius;`
`  float intersectDistance = centerProjDist + sqrt (sr2−dcpc2);`
`  if (intersectDistance >0.0)`
`    currentDistance = intersectionDistance;`
`}`

Some variable names in this algorithm are the same as those in the Clip Front algorithm inherent in Ray Init, such as `currentDistance`. But neither of these two algorithms can run normally. I want to know if the variable names in the software have changed?
Thank you again for your attention to my question.

(If you have time to help me debug the code successfully, I would be very grateful  :-D)

**Comment by hgueziri** [comment]
@Blazer7 The algorithm parts implemented in the GUI can be found in [IbisPlugins/PRISMVolumeRender/volumerenderingobject.cpp](https://github.com/IbisNeuronav/Ibis/blob/570b4a66d05190bbc6c757d72a0037f67b228a14/IbisPlugins/PRISMVolumeRender/volumerenderingobject.cpp#L42)
You might also be interested in checking [IbisPlugins/PRISMVolumeRender/vtkPRISMVolumeRaycast_FS.glsl](https://github.com/IbisNeuronav/Ibis/blob/master/IbisPlugins/PRISMVolumeRender/vtkPRISMVolumeRaycast_FS.glsl), it contains the core algorithm code.
@drouin-simon correct me if I am wrong, I am not familiar with that part of the code.

**Comment by Blazer7** [comment]
Anyway, thank you very much.
